---
development:
  cloud_name: dt5tuiuls
  api_key: '793232633114445'
  api_secret: ZZb5Lnc_rQe9X7ymdaZ4WiQIXxs
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dt5tuiuls
  api_key: '793232633114445'
  api_secret: ZZb5Lnc_rQe9X7ymdaZ4WiQIXxs
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dt5tuiuls
  api_key: '793232633114445'
  api_secret: ZZb5Lnc_rQe9X7ymdaZ4WiQIXxs
  enhance_image_tag: true
  static_file_support: false
